title: RIBows
description: Clubs and RIOs for the UH Community
google_analytics:
show_downloads: false
theme: jekyll-theme-slate
github:
  is_project_page: true
  repository_url: https://github.com/RI-Bows/ri-bows.github.io
gems:
  - jekyll-mentions
